config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :students
  resources :classrooms do
    resources :assignments
  end

  get "/student_session" => "classrooms#student_session"
  get "/submit_assignment/:classroom_id/:assignment_id" => "assignments#submit_assignment"

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

  belongs_to :classroom
  has_many :submissions
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base

  validates :name, :presence => true

  belongs_to :student
  has_many :assignments, dependent: :destroy
end

app/models/student.rb
class Student < ActiveRecord::Base

  validates :name, :presence => true

  has_many :classrooms
  has_many :assignments, :through => :classrooms
  has_many :submissions

end

app/models/submission.rb
class Submission < ActiveRecord::Base

  belongs_to :student
  belongs_to :assignment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  # GET    /classrooms/:classroom_id/assignments
  def index
    @classroom = Classroom.find(params[:classroom_id])
    #@assignments = Assignment.where(:classroom_id => params[:classroom_id]).all
    @assignments = @classroom.assignments
  end

  # GET    /classrooms/:classroom_id/assignments/new
  def new
    @classroom = Classroom.find(params[:classroom_id])
    @assignment = @classroom.assignments.build
  end

  # POST   /classrooms/:classroom_id/assignments
  def create
    @classroom = Classroom.find(params[:classroom_id])
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to classrooms_url, :notice => 'Assignment was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # GET /assignment/1
  def show
    @assignment = Assignment.find(params[:id])
  end

  # DELETE /classrooms/:classroom_id/assignments/:id
  def destroy

  end

  # GET /submit_assignment/:classroom_id/:assignment_id
  def submit_assignment
    # Here I have taken student_id by default "2" once student will login through authenticate way then it will be current_user.id
    submission = Submission.create(:assignment_id => params[:assignment_id], :student_id => "2")

    redirect_to classroom_assignments_path(params[:classroom_id])
  end

  private

  # allow white listed params for assignment
  def assignment_params
    params.require(:assignment).permit(:name, :description, :classroom_id)
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController

  def student_session
    session[:role] = "student"
    redirect_to classrooms_url
  end

  # GET /classrooms
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1
  def show
    @classroom = Classroom.find(params[:id])
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to classrooms_url, :notice => 'Classroom was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    Classroom.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, :notice => 'Classroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # allow white listed params for classroom
  def classroom_params
    params.require(:classroom).permit(:name, :description)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  # GET /students/new
  def new
    @student = Student.new
  end


  def show
    @student = Student.find(params[:id])
  end

  # POST /students
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_url, :notice => 'Student was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    Student.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to students_url, :notice => 'Student was successfully destroyed.' }
    end
  end

  private

  # allow white listed params for student
  def student_params
    params.require(:student).permit(:name, :course, :roll_no)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    session[:role] = ""
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assignments/index.html.erb
<h3>Assignments List</h3>

<%= params[:notice] if params[:notice] %>

<% if !@assignments.empty? %>

  <% if session[:role].blank? %>
    <%= link_to "Add Assignment", new_classroom_assignment_path %> <br/><br/>
  <% end %>

  <table border="1">

    <tr>
      <td><b>Name</b></td>
      <td><b>Description</b></td>
      <td colspan="2"></td>
    </tr>

    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.name %></td>
        <td><%= assignment.description %></td>
        <td><%= link_to 'Show', classroom_assignment_path(@classroom, assignment) %></td>
        <td><%= link_to 'Submit', "/submit_assignment/#{@classroom.id}/#{assignment.id}" %></td>
      </tr>
    <% end %>
  </table>

<% else %>
  <h4> No Assignments available</h4>
  <% if session[:role].blank? %>
    <p> Add Assignments from here: <%= link_to "Add Assignment", new_classroom_assignment_path %></p>
  <% end %>
<% end %>

<br/><br/>

<%= link_to 'Back to Home', root_path %>

app/views/assignments/new.html.erb
<h1> New Assignment</h1>

<%= form_for [@classroom, @assignment] do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :classroom_id %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/assignments/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @assignment.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @assignment.description %>
</p>

<p>
  <strong>Description:</strong>
  <%= @assignment.description %>
</p>


<%= link_to 'Back', classrooms_path %>

app/views/classrooms/index.html.erb
<h3>Classrooms List</h3>

<%= params[:notice] if params[:notice] %>

  <% if !@classrooms.empty? %>
    <% if session[:role].blank? %>
      <%= link_to "Add Classroom", new_classroom_path %> <br/><br/>
    <% end %>

    <table border="1">

      <tr>
        <td><b>Name</b></td>
        <td><b>Description</b></td>
        <td colspan="4"></td>
      </tr>

      <% @classrooms.each do |classroom| %>
        <tr>
          <td><%= classroom.name %></td>
          <td><%= classroom.description %></td>
          <td><%= link_to 'Show', classroom %></td>
          <% if session[:role].blank? %>
            <td><%= link_to 'Destroy', classroom, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
            <td><%= link_to 'Add Assignments',new_classroom_assignment_path(classroom) %></td>
          <% end %>
          <td><%= link_to 'Assignments',classroom_assignments_path(classroom)  %></td>
        </tr>
      <% end %>
    </table>

  <% else %>
    <h4> No Classrooms available</h4>
    <% if session[:role].blank? %>
      <p>Add Classrooms from here: <%= link_to "Add Classroom", new_classroom_path %></p>
    <% end %>
  <% end %>

<br/><br/>

<%= link_to 'Back to Home', root_path %>

app/views/classrooms/new.html.erb
<h1>New classroom</h1>

<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation" class="error">
      <h2>Error found from being saved: <%= pluralize(@classroom.errors.count, "error") %> </h2>

      <ul>
        <% @classroom.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @classroom.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @classroom.description %>
</p>


<%= link_to 'Back', classrooms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BacancyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/index.html.erb
<h3>Students List</h3>

<%= params[:notice] if params[:notice] %>

  <% if !@students.empty? %>
    <% if session[:role].blank? %>
      <%= link_to "Add Student", new_student_path %> <br/>
    <% end %>
    <br/>
    <table border="1">
      <tr>
        <td><b>Name</b></td>
        <td><b>Course</b></td>
        <td><b>Roll no</b></td>
        <td colspan="2"></td>
      </tr>

      <% @students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.course %></td>
          <td><%= student.roll_no %></td>
          <td><%= link_to 'Show', student %></td>
          <% if session[:role].blank? %>
            <td><%= link_to 'Destroy', student, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </table>

  <% else %>

    <h4> No Students available</h4>
    <% if session[:role].blank? %>
      <p>Add Students from here: <%= link_to "Add Students", new_student_path %></p>
    <% end %>

  <% end %>

<hr/>

<%= link_to "Classrooms", classrooms_path %> <br/>
<hr/>
<%= link_to 'Back to Home', root_path %>

app/views/students/new.html.erb
<h2>New student</h2>

<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation" class="error">
      <h2>Error found from being saved: <%= pluralize(@student.errors.count, "error") %> </h2>

      <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :roll_no %><br>
    <%= f.number_field :roll_no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course %>
</p>

<p>
  <strong>Roll no:</strong>
  <%= @student.roll_no %>
</p>


<%= link_to 'Back', students_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Bacancy Test</h1>

<p><%= link_to "Student", student_session_path %></p>

<p><%= link_to "Admin User", students_path %></p>